/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  guideSidebar:[
    {
      type: "category",
      label: "📜 Introduction",
      link: {type: 'doc', id: 'guide/introduction/getting-started'},
      collapsible: true,
      collapsed: true,
      items:[
        "guide/introduction/overview",
        "guide/introduction/tech-zkBNB",
        //"guide/introduction/usage-zkBNB",
        "guide/introduction/fee-structure"
      ],
    },
    {
      type: "category",
      label: "🕶️ Core Concepts",
      collapsible: true,
      collapsed: true,
      items:[
        "guide/core-concepts/overview",
        "guide/core-concepts/zkbnb-arch",
        "guide/core-concepts/protocol",
      ]
    },
    {
      type: "category",
      label: "📦 Storage",
      collapsible: true,
      collapsed: true,
      items:[
        "guide/storage/storage-layout"
      ]
    },
    {
      type: "category",
      label: "💰 Economics",
      collapsible: true,
      collapsed: true,
      items:[
        "guide/economics/gas-and-fees",
        "guide/economics/tokenomics"
      ]
    },
    {
      type: "category",
      label: "💼 Products",
      collapsible: true,
      collapsed: true,
      items:[
        {
          type: "category",
          label: "💳 zkBNB Wallet",
          collapsible: true,
          collapsed: true,
          items:[
            "guide/zkbnb-wallet/overview",
            //"guide/zkbnb-wallet/wallet-configuration",
            "guide/zkbnb-wallet/get-test-tokens",
          ]
        },
        {
          type: "category",
          label: "🏬 zkBNB Marketplace",
          collapsible: true,
          collapsed: true,
          items:[
            "guide/zkbnb-marketplace/overview",
            //"guide/zkbnb-marketplace/deposit-bnb",
            //"guide/zkbnb-marketplace/create-nfts",
            //"guide/zkbnb-marketplace/create-collections",
          ]
        }
      ]
    },
    {
        type: "category",
        label: "🎯 Build on zkBNB",
        collapsible: true,
        collapsed: true,
        items:[
          "guide/build-on-zkbnb/resources",
         // "guide/build-on-zkbnb/hardware-reqs",
         // "guide/build-on-zkbnb/software-reqs",
          {type: 'doc', label:'zkBNB SDKs', id:'sdks/zkbnb-go-sdk/quickstart'},
        ]
    },
    {
      type: "category",
      label: "👩‍🏫 Tutorials",
      collapsible: true,
      collapsed: true,
      items:[
        
        "guide/zkbnb-wallet/get-test-tokens",
        //"guide/tutorials/fund-zkbnb-wallet",
        //"guide/tutorials/nft-minting",
      ]
    },
    {
      type: "category",
      label: "🧑‍🔧 Troubleshooting",
      collapsible: true,
      collapsed: true,
      items:[
        //"guide/troubleshooting/common-errors",
        "faqs/zkbnb-faqs"
      ]
    },
    {type:'doc', id:'guide/contact-us', label: "☎️ Contact Us"},
  ],

  sdkSidebar:[
    {
      type: "category",
      label: "🧮 zkBNB SDKs",
      link: {
        type: 'generated-index',
        title: 'zkBNB SDKs',
        description: 'Explore the different zkBNB SDKs for jump starting your development on zkBNB!',
        slug: '/zkbnb-sdk-guides',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
        //type: 'doc', id: 'sdks/zkbnb-sdks'
      },
      collapsible: true,
      collapsed: true,
      items:[
      "sdks/zkbnb-go-sdk/quickstart",
      "sdks/zkbnb-js-sdk/quickstart",
      "sdks/zkbnb-ts-sdk/quickstart",
      "sdks/zkbnb-web-sdk/quickstart",
      ]
    },
    {
      type: 'category',
      label: "👩‍🏫 Tutorials",
      items:[
        "sdks/tutorials/reactjs-integration-example/reactjs-integration-example"
      ]
    }
  ],

  faqSidebar:[
    {
      type:"category", 
      label: "🧙 FAQs",
      link: {type: 'doc', id: 'faqs/zkbnb-faqs'},
      collapsible: true,
      collapsed: true,
      items:[
        {type: 'doc', id:'faqs/platform', label: 'Platform'},
        {type: 'doc', id:'faqs/tokenomics', label: 'Tokenomics'},
        {type: 'doc', id:'faqs/gas-and-fees', label: 'Gas and Fees'},
        {type: 'doc', id:'faqs/onboarding', label: 'Onboarding'},
        {type: 'doc', id:'faqs/contract', label: 'Contract'},
        {type: 'doc', id:'faqs/minting-and-royalities', label: 'Miniting and Royalities'},
        {type: 'doc', id:'faqs/asset-management', label: 'Asset Management'},
      ]
    },
  ],

  openApiSidebar: [
    {
      type: "category",
      label: "💻 zkBNB API",
      link: {
        type: "generated-index",
        title: "zkBNB API",
        description:
          "zkBNB is a ground-breaking scaling solution form BNB Chain, built on ZK (Zero Knowledge) Rollup architecture. BNB Chain provides a set of APIs to developers for accessing zkBNB. This is the official documentation of public APIs for zkBNB",
        slug: "/zkbnb-api"
      },
      // @ts-ignore
      items: require("./docs/zkbnb/sidebar.js")
    },
  ]
};

module.exports = sidebars;
