/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  openApiSidebar: [
    {
      type: "category",
      label: "zkBNB API",
      link: {
        type: "generated-index",
        title: "zkBNB API",
        description:
          "zkBNB is a ground-breaking scaling solution form BNB Chain, built on ZK (Zero Knowledge) Rollup architecture. BNB Chain provides a set of APIs to developers for accessing zkBNB. This is the official documentation of public APIs for zkBNB",
        slug: "/zkbnb-api"
      },
      // @ts-ignore
      items: require("./docs/zkbnb/sidebar.js")
    },
  ]
};

module.exports = sidebars;
